# Generated by Django 6.0.1 on 2026-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('done', 'Done')], default='new', max_length=10),
        ),
    ]
